use CDNASTG;
SELECT COUNT(*) AS CHANN_TRA_COUNT  FROM channels_tra;
SELECT COUNT(*) AS COUN_TRA_COUNT FROM countries_tra ;
SELECT COUNT(*) AS CUS_TRA_COUNT FROM customers_tra ;
SELECT COUNT(*) AS PROM_TRA_COUNT FROM promotions_tra ;
SELECT COUNT(*) AS PROD_TRA_COUNT FROM products_tra ;
SELECT COUNT(*) AS TIMES_TRA_COUNT FROM times_tra ;
SELECT COUNT(*) AS SALES_TRA_COUNT FROM sales_tra ;

